workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Decode Firebase plist
        script: |
          echo $GOOGLE_SERVICE_INFO | base64 --decode > ios/Runner/GoogleService-Info.plist

      - name: Generate iOS project files
        script: |
          flutter build ios --release --no-codesign

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

    artifacts:
      - build/ios/iphoneos/*.app
