// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB3e5-M35NPtOynJVoObMj6bSibWbyIKw',
    appId: '1:292872026411:web:ca5e827f5ae7c128072d6e',
    messagingSenderId: '292872026411',
    projectId: 'my-cool-notes-app-devraj5677',
    authDomain: 'my-cool-notes-app-devraj5677.firebaseapp.com',
    storageBucket: 'my-cool-notes-app-devraj5677.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv1NKOJBj-BIqJyUm60n5X-VukkG2BTV4',
    appId: '1:292872026411:android:be2bd0e0bab87468072d6e',
    messagingSenderId: '292872026411',
    projectId: 'my-cool-notes-app-devraj5677',
    storageBucket: 'my-cool-notes-app-devraj5677.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDGvl4rH6Tlf4WyktsPO-S_-ZP4K4yeD8',
    appId: '1:292872026411:ios:e276eee40e2ad369072d6e',
    messagingSenderId: '292872026411',
    projectId: 'my-cool-notes-app-devraj5677',
    storageBucket: 'my-cool-notes-app-devraj5677.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB3e5-M35NPtOynJVoObMj6bSibWbyIKw',
    appId: '1:292872026411:web:3c0a2ad6dad302dc072d6e',
    messagingSenderId: '292872026411',
    projectId: 'my-cool-notes-app-devraj5677',
    authDomain: 'my-cool-notes-app-devraj5677.firebaseapp.com',
    storageBucket: 'my-cool-notes-app-devraj5677.firebasestorage.app',
  );
}
