# ios/Podfile

platform :ios, '12.0'

# Use static linking for compatibility with Firebase plugins
use_frameworks! :linkage => :static

# Disable CocoaPods analytics
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Define path to Flutter app
flutter_application_path = '../'
# load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

# Main app target
target 'Runner' do
  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end
