name: build-ios

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'

      - name: Flutter pub get
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --release --no-codesign


      - name: Upload IPA as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa
